### PR TITLE
Draft: Upgrade Unity headers to 6000.0.5f1, add `IUnityMemoryManager.h`, `IU…

### PR DESCRIPTION
**Pull request by ZhaoXiangXML**
…nityEventQueue.h` and `IUnityLog.h` to generated bindings

### CODE REVIEW

**Comment by ZhaoXiangXML** [comment]
I've re-generated bindings with headers from Unity 6 (6000.0.5), with three additional headers:

```cpp

#include <IUnityMemoryManager.h>
Assert(bool);
#include <IUnityEventQueue.h>
#include <IUnityLog.h>
```

**Comment by ZhaoXiangXML** [comment]
@wlgys8 Would you please kindly review it?

**Comment by wlgys8** [comment]
good job

**Comment by ZhaoXiangXML** [comment]
I'll send a PR to upstream instead.

**Pull request closed without merging**
